import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { BookstoreThemeWrapper, NavbarStyled } from "@/components/BookstoreTheme";
import { Toaster } from "@/components/ui/toast/toaster";
import Providers from "./providers";
import SessionProvider from "./(main)/SessionProvider";

export const metadata: Metadata = {
  title: "BookVerse",
  description: "Generated by CodeezaDevs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <><link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" /><link rel="icon" type="image/svg+xml" href="/favicon.svg" /><link rel="shortcut icon" href="/favicon.ico" /><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" /><link rel="manifest" href="/site.webmanifest" /></>

      <body>
        <Providers>
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <BookstoreThemeWrapper>
              <NavbarStyled>
              {/* children={undefined} */}
              </NavbarStyled>
              <main className="max-w-7xl mx-auto p-6">
                {children}
              </main>
              <Toaster />
            </BookstoreThemeWrapper>
          </ThemeProvider>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
